# ============================================================================ #
#                         PNPM Workspace Configuration                         #
# ============================================================================ #
# This file defines the configuration for the pnpm workspace, which is a       #
# package management tool for JavaScript projects.                             #
#                                                                              #
# See: https://pnpm.io/settings                                                #
# ============================================================================ #

minimumReleaseAge: 0

packages:
  - "packages/*"

update:
  githubActions: true

overrides:
  "@octalmesh/seagull-core": "workspace:*"
  "@octalmesh/seagull-cli": "workspace:*"
  "@octalmesh/seagull-docs": "workspace:*"

allowBuilds:
  "@openapitools/openapi-generator-cli": true
  esbuild: true
  vue-demi: true
