import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

import type { ResolvedConfig } from "@config/types";

const GENERATED_HEADER =
  "# AUTO-GENERATED by Seagull from its config and 'redocly.base.yaml'.\n" +
  "# Do not edit directly, edit those two files instead (this file is\n" +
  "# regenerated on every lint/bundle/generate run).\n\n";

interface RedoclyBase {
  extends?: string[];
  rules?: Record<string, string>;
}

/**
 * Regenerates `redocly.yaml`'s `apis:` section from the resolved CLI config,
 * merging it with the hand-authored `extends`/`rules` in `redocly.base.yaml`.
 *
 * The CLI config stays the single source of truth for which APIs exist and
 * where their TypeScript server types land, instead of that being duplicated
 * by hand into `redocly.yaml`.
 *
 * Called at the start of every command that shells out to `redocly` or
 * `openapi-typescript` (both read `redocly.yaml` directly), so it's always
 * up to date before those tools run.
 *
 * @param config - The resolved CLI config.
 */
export async function syncRedoclyConfig(config: ResolvedConfig): Promise<void> {
  const basePath = path.join(config.rootDir, "redocly.base.yaml");
  const base = parseYaml(await readFile(basePath, "utf8")) as RedoclyBase;

  const apis = Object.fromEntries(
    config.contracts.map((contract) => {
      const typesArtifact = contract.artifacts.find(
        (artifact) => artifact.tool === "openapi-typescript",
      );

      return [
        `${contract.name}@v1`,
        {
          root: contract.entrypointRelative,
          ...(typesArtifact
            ? {
                "x-openapi-ts": {
                  output: path.join(
                    path.relative(config.rootDir, typesArtifact.outputDir),
                    "index.d.ts",
                  ),
                },
              }
            : {}),
        },
      ];
    }),
  );

  const final = { extends: base.extends, apis, rules: base.rules };

  await writeFile(
    path.join(config.rootDir, "redocly.yaml"),
    GENERATED_HEADER + stringifyYaml(final),
  );
}
