import { spawn } from "node:child_process";
import { readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { afterAll, beforeAll, describe, expect, it } from "vitest";

import {
  CLI_ENTRY,
  canReach,
  copyFixture,
  initGitOrigin,
  listRefs,
  readJson,
  run,
  runCli,
} from "./support/harness";

describe("seagull e2e: full pipeline against a real contracts fixture", () => {
  //<editor-fold desc="Default pipeline" defaultstate="collapsed">
  describe("lint / bundle / generate / docs, run in sequence", () => {
    let dir: string;

    beforeAll(async () => {
      dir = await copyFixture("pipeline");
    });

    afterAll(async () => {
      await rm(dir, { recursive: true, force: true });
    });

    //<editor-fold desc="Lint" defaultstate="collapsed">
    it("lints both real contracts cleanly with the actual redocly CLI", () => {
      const result = runCli(["lint"], dir);

      expect(result.stdout).toContain("Checking [auth]...");
      expect(result.stdout).toContain("Checking [catalog]...");
      expect(result.stderr).toContain("Woohoo! Your API description is valid");
      expect(result.status).toBe(0);
    });
    //</editor-fold>

    //<editor-fold desc="Bundle" defaultstate="collapsed">
    it("bundles both contracts into dist/specs via the real redocly CLI", async () => {
      const result = runCli(["bundle"], dir);

      expect(result.status).toBe(0);
      expect(result.stdout).toContain("Bundled 2 specifications");

      const authSpec = await readJson<{
        info: { title: string; version: string };
      }>(dir, "dist", "specs", "auth.json");

      expect(authSpec.info.title).toBe("Auth Service API");
      expect(authSpec.info.version).toBe("0.1.0");
    });

    it("resolves $ref-split multi-file specs correctly (shared components, nested paths)", async () => {
      const authSpec = await readJson<{
        paths: Record<string, unknown>;
        components: { schemas: Record<string, unknown> };
      }>(dir, "dist", "specs", "auth.json");

      expect(Object.keys(authSpec.paths).sort()).toEqual(["/login", "/me"]);
      expect(authSpec.components.schemas).toHaveProperty("User");
      expect(authSpec.components.schemas).toHaveProperty("Token");
      expect(authSpec.components.schemas).toHaveProperty("LoginRequest");
    });
    //</editor-fold>

    //<editor-fold desc="Generate" defaultstate="collapsed">
    it("generates real openapi-typescript output for every artifact", () => {
      const result = runCli(["generate"], dir);

      expect(result.status).toBe(0);
      expect(result.stdout).toContain("Generated 2 SDK packages");
      expect(result.stdout).toContain("auth@0.1.0");
      expect(result.stdout).toContain("catalog@0.2.0");
    });

    it("writes a real, well-formed .d.ts with the expected operation types", async () => {
      const dts = await readFile(
        path.join(dir, "dist", "sdk", "auth", "ts-server", "index.d.ts"),
        "utf8",
      );

      expect(dts).toContain(
        "This file was auto-generated by openapi-typescript",
      );
      expect(dts).toContain('"/login"');
      expect(dts).toContain('"/me"');
      expect(dts).toContain("operations");
    });

    it("renders the artifact's custom README template (not the built-in default)", async () => {
      const readme = await readFile(
        path.join(dir, "dist", "sdk", "auth", "ts-server", "README.md"),
        "utf8",
      );

      expect(readme).toBe(
        [
          "# Auth Service API (types-only)",
          "",
          "> Custom README template test fixture - not the built-in default.",
          "",
          "- Service: `auth`",
          "- Artifact: `ts-server`",
          "- Version: `0.1.0`",
          "- Package: `@octalmesh/auth-server`",
          "- Org: `octalmesh`",
          "- Repo: `OctalMesh/ows-contracts-e2e-fixture`",
          "",
          "```ts",
          'import type { components } from "@octalmesh/auth-server";',
          "```",
          "",
        ].join("\n"),
      );
    });

    it("writes package.json with the resolved version, repository, and publishConfig", async () => {
      const pkg = await readJson<Record<string, unknown>>(
        dir,
        "dist",
        "sdk",
        "catalog",
        "ts-server",
        "package.json",
      );

      expect(pkg).toMatchObject({
        name: "@octalmesh/catalog-server",
        version: "0.2.0",
        repository: {
          type: "git",
          url: "git+https://github.com/OctalMesh/ows-contracts-e2e-fixture.git",
        },
        publishConfig: {
          registry: "https://npm.pkg.github.com",
          access: "public",
        },
      });
    });
    //</editor-fold>

    //<editor-fold desc="Docs" defaultstate="collapsed">
    it("generates the docs site, embedding both contracts and copying the real Scalar bundle", async () => {
      const result = runCli(["docs", "generate"], dir);

      expect(result.status).toBe(0);

      const html = await readFile(
        path.join(dir, "dist", "docs", "index.html"),
        "utf8",
      );

      expect(html).toContain('title: "OWS E2E Docs"');
      expect(html).toContain('slug: "auth"');
      expect(html).toContain('slug: "catalog"');

      const scalarJs = await readFile(
        path.join(dir, "dist", "docs", "scalar.js"),
        "utf8",
      );

      expect(scalarJs.length).toBeGreaterThan(1000);
    });

    it("serves the generated docs site over real HTTP", async () => {
      const child = spawn("node", [CLI_ENTRY, "docs", "serve"], {
        cwd: dir,
        stdio: ["ignore", "pipe", "pipe"],
      });

      try {
        await new Promise<void>((resolveReady, rejectReady) => {
          let buffered = "";

          const onData = (chunk: Buffer): void => {
            buffered += chunk.toString();

            if (buffered.includes("Scalar documentation:")) {
              child.stdout?.off("data", onData);
              resolveReady();
            }
          };

          child.stdout?.on("data", onData);
          child.on("error", rejectReady);
          child.on("exit", (code) => {
            rejectReady(new Error(`docs serve exited early with ${code}`));
          });

          setTimeout(
            () => rejectReady(new Error("timed out waiting for docs serve")),
            10_000,
          );
        });

        const indexRes = await fetch("http://127.0.0.1:4173/");
        const specRes = await fetch("http://127.0.0.1:4173/specs/catalog.json");
        const missingRes = await fetch("http://127.0.0.1:4173/does-not-exist");

        expect(indexRes.status).toBe(200);
        expect(await indexRes.text()).toContain("OWS E2E Docs");
        expect(specRes.status).toBe(200);
        expect(missingRes.status).toBe(404);
      } finally {
        child.kill();
      }
    });
    //</editor-fold>

    //<editor-fold desc="Clean" defaultstate="collapsed">
    it("removes dist/ entirely on clean", async () => {
      const result = runCli(["clean"], dir);

      expect(result.status).toBe(0);
      await expect(
        readFile(path.join(dir, "dist", "specs", "auth.json")),
      ).rejects.toThrow();
    });
    //</editor-fold>
  });
  //</editor-fold>

  //<editor-fold desc="Lint failure" defaultstate="collapsed">
  describe("lint failure surfaces the real redocly diagnostic and a non-zero exit code", () => {
    let dir: string;

    beforeAll(async () => {
      dir = await copyFixture("lint-failure");

      const productsPath = path.join(
        dir,
        "specs",
        "catalog",
        "paths",
        "products.yaml",
      );
      const original = await readFile(productsPath, "utf8");
      const broken = original
        .split("\n")
        .filter((line) => !line.trim().startsWith("operationId:"))
        .join("\n");

      await writeFile(productsPath, broken);
    });

    afterAll(async () => {
      await rm(dir, { recursive: true, force: true });
    });

    it("fails with a real redocly rule violation when a spec is broken", () => {
      const result = runCli(["lint"], dir);

      expect(result.status).not.toBe(0);
      expect(result.stderr).toMatch(/operation-operationId|Validation failed/);
    });
  });
  //</editor-fold>

  //<editor-fold desc="Publish SDK" defaultstate="collapsed">
  describe("publish sdk against a real local git remote", () => {
    let dir: string;
    let originDir: string;

    beforeAll(async () => {
      dir = await copyFixture("publish");
      originDir = await initGitOrigin(dir);

      expect(runCli(["bundle"], dir).status).toBe(0);
      expect(runCli(["generate"], dir).status).toBe(0);
    });

    afterAll(async () => {
      await rm(dir, { recursive: true, force: true });
      await rm(originDir, { recursive: true, force: true });
    });

    it("creates real orphan branches and tags on first publish", () => {
      const result = runCli(["publish", "sdk"], dir);

      expect(result.status).toBe(0);
      expect(result.stdout).toContain(
        "Published sdk/svc-auth/ts-server @ svc-auth-ts-server-v0.1.0",
      );
      expect(result.stdout).toContain(
        "Published sdk/svc-catalog/ts-server @ svc-catalog-ts-server-v0.2.0",
      );

      expect(listRefs(originDir, "heads").sort()).toEqual([
        "sdk/svc-auth/ts-server",
        "sdk/svc-catalog/ts-server",
      ]);
      expect(listRefs(originDir, "tags").sort()).toEqual([
        "svc-auth-ts-server-v0.1.0",
        "svc-catalog-ts-server-v0.2.0",
      ]);
    });

    it("actually pushed the generated package contents, not just an empty commit", () => {
      const catFile = run(
        "git",
        ["show", "sdk/svc-auth/ts-server:package.json"],
        originDir,
      );
      const pkg = JSON.parse(catFile) as Record<string, unknown>;

      expect(pkg.name).toBe("@octalmesh/auth-server");
    });

    it("is idempotent: re-running publish with unchanged specs skips (no new commit)", () => {
      const before = run(
        "git",
        ["rev-parse", "sdk/svc-auth/ts-server"],
        originDir,
      );

      const result = runCli(["publish", "sdk"], dir);

      const after = run(
        "git",
        ["rev-parse", "sdk/svc-auth/ts-server"],
        originDir,
      );

      expect(result.status).toBe(0);
      expect(result.stdout).toContain("already published");
      expect(after).toBe(before);
    });

    it("detects real spec-content drift under an unchanged version and refuses to overwrite the tag", async () => {
      const productsPath = path.join(
        dir,
        "specs",
        "catalog",
        "paths",
        "products.yaml",
      );
      const original = await readFile(productsPath, "utf8");

      await writeFile(
        productsPath,
        original.replace(
          'summary: "List catalog products"',
          'summary: "List catalog products (edited, same version)"',
        ),
      );

      try {
        expect(runCli(["bundle"], dir).status).toBe(0);
        expect(runCli(["generate"], dir).status).toBe(0);

        const result = runCli(["publish", "sdk"], dir);

        expect(result.status).not.toBe(0);
        expect(result.stderr).toMatch(
          /already exists, but the catalog spec content has changed/,
        );
      } finally {
        await writeFile(productsPath, original);
      }
    });
  });
  //</editor-fold>

  //<editor-fold desc="Publish registries" defaultstate="collapsed">
  describe("publish registries --dry-run never touches a real registry", () => {
    let dir: string;

    beforeAll(async () => {
      dir = await copyFixture("registries");

      expect(runCli(["bundle"], dir).status).toBe(0);
      expect(runCli(["generate"], dir).status).toBe(0);
    });

    afterAll(async () => {
      await rm(dir, { recursive: true, force: true });
    });

    it("prints the npm publish commands it would run, without executing them", () => {
      const result = runCli(["publish", "registries", "--dry-run"], dir);

      expect(result.status).toBe(0);
      expect(result.stdout).toContain("npm publish");
      expect(result.stdout).toContain("published 2 registry package(s)");
    });
  });
  //</editor-fold>

  //<editor-fold desc="OpenAPI Generator CLI" defaultstate="collapsed">
  describe("openapi-generator-cli-backed artifacts (requires Maven Central access)", () => {
    it("generates a real typescript-fetch client via the real openapi-generator-cli tool", async (context) => {
      if (!(await canReach("https://repo1.maven.org/maven2/"))) {
        context.skip();

        return;
      }

      const dir = await copyFixture("openapi-generator-cli");

      try {
        const configPath = path.join(dir, "seagull.yaml");
        const original = await readFile(configPath, "utf8");

        await writeFile(
          configPath,
          original.replace(
            'artifacts:\n      - "ts-server"\n\n  - name: "catalog"',
            'artifacts:\n      - "ts-server"\n      - "ts-client"\n\n  - name: "catalog"',
          ),
        );

        expect(runCli(["bundle"], dir).status).toBe(0);

        const result = runCli(["generate"], dir);

        expect(result.status).toBe(0);

        const pkg = await readJson<Record<string, unknown>>(
          dir,
          "dist",
          "sdk",
          "auth",
          "ts-client",
          "package.json",
        );

        expect(pkg.name).toBe("@octalmesh/auth-client");
        expect(pkg.version).toBe("0.1.0");
      } finally {
        await rm(dir, { recursive: true, force: true });
      }
    }, 120_000);
  });
  //</editor-fold>
});
