import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";

import type { ResolvedConfig } from "../config/types";
import { GITHUB, makeArtifact, makeContract } from "../test-support/fixtures";
import { syncRedoclyConfig } from "./redocly-sync";

function makeConfig(overrides: Partial<ResolvedConfig> = {}): ResolvedConfig {
  return {
    configVersion: 1,
    rootDir: "/repo",
    paths: {
      dist: "/repo/dist",
      specs: "/repo/dist/specs",
      docs: "/repo/dist/docs",
      sdk: "/repo/dist/sdk",
    },
    github: GITHUB,
    vars: {},
    docs: {
      server: { host: "localhost", port: 8080 },
      metadata: {
        title: "t",
        description: "d",
        favicon: "f",
        baseServerUrl: "https://example.com",
      },
    },
    contracts: [makeContract()],
    allArtifacts: [],
    ...overrides,
  };
}

describe("syncRedoclyConfig", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(path.join(tmpdir(), "seagull-redocly-"));
    await writeFile(
      path.join(dir, "redocly.base.yaml"),
      [
        "extends:",
        '  - "recommended"',
        "rules:",
        '  operation-operationId: "error"',
      ].join("\n"),
    );
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it("writes redocly.yaml merging the base extends/rules with generated apis", async () => {
    const config = makeConfig({ rootDir: dir });

    await syncRedoclyConfig(config);

    const written = await readFile(path.join(dir, "redocly.yaml"), "utf8");
    const parsed = parseYaml(written) as {
      extends: string[];
      rules: Record<string, string>;
      apis: Record<string, unknown>;
    };

    expect(parsed.extends).toEqual(["recommended"]);
    expect(parsed.rules).toEqual({ "operation-operationId": "error" });
    expect(parsed.apis).toHaveProperty("auth@v1");
  });

  it("prefixes the generated file with the auto-generated header comment", async () => {
    const config = makeConfig({ rootDir: dir });

    await syncRedoclyConfig(config);

    const written = await readFile(path.join(dir, "redocly.yaml"), "utf8");

    expect(written).toMatch(/^# AUTO-GENERATED by Seagull/);
    expect(written).toMatch(/Do not edit directly/);
  });

  it("sets each api's 'root' to the contract's entrypoint relative to rootDir", async () => {
    const config = makeConfig({ rootDir: dir });

    await syncRedoclyConfig(config);

    const parsed = parseYaml(
      await readFile(path.join(dir, "redocly.yaml"), "utf8"),
    ) as { apis: Record<string, { root: string }> };

    expect(parsed.apis["auth@v1"]!.root).toBe("specs/auth/openapi.yaml");
  });

  it("adds x-openapi-ts.output only for contracts with an openapi-typescript artifact", async () => {
    const withTypes = makeContract({
      name: "auth",
      artifacts: [
        makeArtifact({
          tool: "openapi-typescript",
          id: "ts-server",
          outputDir: path.join(dir, "dist", "sdk", "auth", "ts-server"),
        }),
      ],
    });
    const withoutTypes = makeContract({
      name: "catalog",
      entrypoint: "/repo/specs/catalog/openapi.yaml",
      entrypointRelative: path.join("specs", "catalog", "openapi.yaml"),
      artifacts: [
        makeArtifact({
          tool: "openapi-generator",
          id: "java-client",
        }),
      ],
    });

    const config = makeConfig({
      rootDir: dir,
      contracts: [withTypes, withoutTypes],
    });

    await syncRedoclyConfig(config);

    const parsed = parseYaml(
      await readFile(path.join(dir, "redocly.yaml"), "utf8"),
    ) as {
      apis: Record<string, { "x-openapi-ts"?: { output: string } }>;
    };

    expect(parsed.apis["auth@v1"]!["x-openapi-ts"]).toEqual({
      output: path.join("dist", "sdk", "auth", "ts-server", "index.d.ts"),
    });
    expect(parsed.apis["catalog@v1"]!["x-openapi-ts"]).toBeUndefined();
  });

  it("includes every contract as its own '<name>@v1' api entry", async () => {
    const config = makeConfig({
      rootDir: dir,
      contracts: [
        makeContract({ name: "auth" }),
        makeContract({
          name: "catalog",
          entrypoint: "/repo/specs/catalog/openapi.yaml",
          entrypointRelative: path.join("specs", "catalog", "openapi.yaml"),
        }),
      ],
    });

    await syncRedoclyConfig(config);

    const parsed = parseYaml(
      await readFile(path.join(dir, "redocly.yaml"), "utf8"),
    ) as { apis: Record<string, unknown> };

    expect(Object.keys(parsed.apis).sort()).toEqual(["auth@v1", "catalog@v1"]);
  });

  it("rejects when redocly.base.yaml is missing", async () => {
    const emptyDir = await mkdtemp(
      path.join(tmpdir(), "seagull-redocly-empty-"),
    );

    try {
      await expect(
        syncRedoclyConfig(makeConfig({ rootDir: emptyDir })),
      ).rejects.toThrow();
    } finally {
      await rm(emptyDir, { recursive: true, force: true });
    }
  });

  it("overwrites a pre-existing redocly.yaml", async () => {
    await writeFile(
      path.join(dir, "redocly.yaml"),
      "# stale content\napis: {}\n",
    );

    await syncRedoclyConfig(makeConfig({ rootDir: dir }));

    const written = await readFile(path.join(dir, "redocly.yaml"), "utf8");

    expect(written).not.toContain("stale content");
    expect(written).toContain("auth@v1");
  });
});
